# Generated by Django 4.0.4 on 2022-05-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_remove_snack_number_alter_snack_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(),
        ),
    ]
